JakeDrinkStoreWeb/Areas/Admin/Controllers/TagController.cs
using JakeDrinkStore.DataAccess;
using JakeDrinkStore.DataAccess.Repository.IRepository;
using JakeDrinkStore.Models;
using JakeDrinkStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JakeDrinkStoreWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
	[Authorize(Roles = SD.Role_Admin)]
	public class TagController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public TagController(IUnitOfWork unitOfWork) 
        {
            _unitOfWork = unitOfWork;
        }

        // GET
        public IActionResult Index()
        {
            IEnumerable<Tag> objCategoryList = _unitOfWork.Tag.GetAll().OrderByDescending(tag => tag.CreatedDateTime); ;
            return View(objCategoryList);
        }

        // GET
        public IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Tag obj)
        {
            bool isExist = await _unitOfWork.Tag.AnyAsync(c => c.Name.ToLower() == obj.Name.ToLower());

            if (isExist)
            {
                ModelState.AddModelError("Name", "The Tag Name already exists.");
                //return BadRequest("The Tag Name already exists");
            }

            if (ModelState.IsValid && !isExist)
            {
                _unitOfWork.Tag.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Tag created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Tag? tagFromDb = _unitOfWork.Tag.GetFirstOrDefault(c => c.Id == id);

            if (tagFromDb == null)
            {
                return NotFound();
            }

            return View(tagFromDb);
        }

        // POST 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Tag obj)
        {
            bool isSameName = await _unitOfWork.Tag.AnyAsync(c => c.Name.ToLower() == obj.Name.ToLower());
            bool isSameDate = await _unitOfWork.Tag.AnyAsync(c => c.CreatedDateTime == obj.CreatedDateTime);

            if (isSameName && isSameDate)
            {
                ModelState.AddModelError("Name", "The Tag Name already exists.");
                ModelState.AddModelError("CreatedDateTime", "The Tag Created Date is the same.");
            }

            if (ModelState.IsValid && (!isSameName || !isSameDate))
            {
                _unitOfWork.Tag.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Tag updated successfully";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        // GET 
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Tag? tagFromDb = _unitOfWork.Tag.GetFirstOrDefault(c => c.Id == id);

            if (tagFromDb == null)
            {
                return NotFound();
            }

            return View(tagFromDb);
        }

        // POST 
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var categoryFromDb = _unitOfWork.Tag.GetFirstOrDefault(u => u.Id == id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            _unitOfWork.Tag.Remove(categoryFromDb);
            _unitOfWork.Save();
            TempData["success"] = "Tag deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

JakeDrinkStoreWeb/Areas/Admin/Views/Tag/Create.cshtml
@model Tag
@{
    ViewData["Title"] = "Create Tag";
}

<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Tag</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="CreatedDateTime"></label>
            <input type="date" asp-for="CreatedDateTime" class="form-control" value="@DateTime.Today.ToString("yyyy-MM-dd")" max="@DateTime.Today.ToString("yyyy-MM-dd")" />
            <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
        <a asp-controller="Tag" asp-action="Index" class="btn btn-secondary" style="width: 150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

JakeDrinkStoreWeb/Areas/Admin/Views/Tag/Delete.cshtml
@model Tag
@{
    ViewData["Title"] = "Delete Tag";
}


<form method="post" asp-action="Delete">
    @*Add this hidden input because in delete fields are disabled*@
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Tag</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" disabled />
        </div>
        <div class="mb-3">
            <label asp-for="CreatedDateTime"></label>
            <input type ="date" asp-for="CreatedDateTime" class="form-control" disabled />
        </div>
        <button type="submit" class="btn btn-danger" style="width: 150px">Delete</button>
        <a asp-controller="Tag" asp-action="Index" class="btn btn-secondary" style="width: 150px">
            Back to List
        </a>
    </div>

</form>

@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

JakeDrinkStoreWeb/Areas/Admin/Views/Tag/Edit.cshtml
@model Tag
@{
    ViewData["Title"] = "Edit Tag";
}


<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Tag</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="CreatedDateTime"></label>
            <input type="date" asp-for="CreatedDateTime" class="form-control" max="@DateTime.Today.ToString("yyyy-MM-dd")" />
            <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width: 150px">Update</button>
        <a asp-controller="Tag" asp-action="Index" class="btn btn-secondary" style="width: 150px">
            Back to List
        </a>
    </div>

</form>

@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

JakeDrinkStoreWeb/Areas/Admin/Views/Tag/Index.cshtml
@model IEnumerable<Tag>
@{
    ViewData["Title"] = "Tags List";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Tags List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Tag" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Tag
            </a>
        </div>
    </div>
    </br>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th width="50%">
                    Tag Name
                </th>
                <th width="30%">
                    Created Date
                </th>
                <th class="text-center" width="10%">Edit</th>
                <th class="text-center" width="10%">Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr class="align-middle">
                    <td>
                        @obj.Name
                    </td>
                    <td>
                        @obj.CreatedDateTime.ToString("dd/MM/yyyy")
                    </td>
                    <td class="text-center">
                        <div class="btn-group" role="group">
                            <a class="btn btn-primary mx-2" asp-controller="Tag" asp-action="Edit" asp-route-id="@obj.Id">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                        </div>
                    </td>
                    <td class="text-center">
                        <div class="btn-group" role="group">
                            <a class="btn btn-danger mx-2" asp-controller="Tag" asp-action="Delete" asp-route-id="@obj.Id">
                                <i class="bi bi-trash3"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>