JakeDrinkStoreWeb/Areas/Admin/Controllers/DrinkTypeController.cs
using JakeDrinkStore.DataAccess.Repository.IRepository;
using JakeDrinkStore.Models;
using JakeDrinkStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JakeDrinkStoreWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
	[Authorize(Roles = SD.Role_Admin)]
	public class DrinkTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public DrinkTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        // GET
        public IActionResult Index()
        {
            IEnumerable<DrinkType> drinkTypeList = _unitOfWork.DrinkType.GetAll().OrderByDescending(drinkType => drinkType.CreatedDateTime);
            return View(drinkTypeList);
        }

        // GET
        public IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DrinkType obj)
        {
            bool isExist = await _unitOfWork.DrinkType.AnyAsync(c => c.Name.ToLower() == obj.Name.ToLower());

            if (isExist)
            {
                ModelState.AddModelError("Name", "The Drink Type already exists.");
            }

            if (ModelState.IsValid && !isExist)
            {
                _unitOfWork.DrinkType.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Drink Type created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET
        public IActionResult Edit(Guid? id)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }

            DrinkType? drinkTypeFromDb = _unitOfWork.DrinkType.GetFirstOrDefault(c => c.Id == id);

            if (drinkTypeFromDb == null)
            {
                return NotFound();
            }

            return View(drinkTypeFromDb);
        }

        // POST 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DrinkType obj)
        {
            bool isSameName = await _unitOfWork.DrinkType.AnyAsync(c => c.Name.ToLower() == obj.Name.ToLower());
            bool isSameDate = await _unitOfWork.DrinkType.AnyAsync(c => c.CreatedDateTime == obj.CreatedDateTime);

            if (isSameName && isSameDate)
            {
                ModelState.AddModelError("Name", "The Drink Type already exists.");
                ModelState.AddModelError("CreatedDateTime", "The Drink Type Created Date is the same.");
            }

            if (ModelState.IsValid && (!isSameName || !isSameDate))
            {
                _unitOfWork.DrinkType.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Drink Type updated successfully";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        // GET 
        public IActionResult Delete(Guid? id)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }

            DrinkType? drinkTypeFromDb = _unitOfWork.DrinkType.GetFirstOrDefault(c => c.Id == id);

            if (drinkTypeFromDb == null)
            {
                return NotFound();
            }

            return View(drinkTypeFromDb);
        }

        // POST 
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(Guid? id)
        {
            var drinkTypeFromDb = _unitOfWork.DrinkType.GetFirstOrDefault(u => u.Id == id);

            if (drinkTypeFromDb == null)
            {
                return NotFound();
            }

            _unitOfWork.DrinkType.Remove(drinkTypeFromDb);
            _unitOfWork.Save();
            TempData["success"] = "Drink Type deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

JakeDrinkStoreWeb/Areas/Admin/Views/DrinkType/Create.cshtml
@model DrinkType

@{
    ViewData["Title"] = "Create Drink Type";
}

<form method="post" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Drink Type</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="CreatedDateTime"></label>
            <input type="date" asp-for="CreatedDateTime" class="form-control" value="@DateTime.Today.ToString("yyyy-MM-dd")" max="@DateTime.Today.ToString("yyyy-MM-dd")" />
            <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
        <a asp-controller="DrinkType" asp-action="Index" class="btn btn-secondary" style="width: 150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

JakeDrinkStoreWeb/Areas/Admin/Views/DrinkType/Delete.cshtml
@model DrinkType
@{
    ViewData["Title"] = "Delete Drink Type";
}

<form method="post" asp-action="Delete">
    @*Add this hidden input because in delete fields are disabled*@
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Drink Type</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" disabled />
        </div>
        <div class="mb-3">
            <label asp-for="CreatedDateTime"></label>
            <input type ="date" asp-for="CreatedDateTime" class="form-control" disabled />
        </div>
        <button type="submit" class="btn btn-danger" style="width: 150px">Delete</button>
        <a asp-controller="DrinkType" asp-action="Index" class="btn btn-secondary" style="width: 150px">
            Back to List
        </a>
    </div>

</form>

@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

JakeDrinkStoreWeb/Areas/Admin/Views/DrinkType/Edit.cshtml
@model DrinkType
@{
    ViewData["Title"] = "Edit Drink Type";
}

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Drink Type</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="CreatedDateTime"></label>
            <input type="date" asp-for="CreatedDateTime" class="form-control" max="@DateTime.Today.ToString("yyyy-MM-dd")" />
            <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width: 150px">Update</button>
        <a asp-controller="DrinkType" asp-action="Index" class="btn btn-secondary" style="width: 150px">
            Back to List
        </a>
    </div>

</form>

@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

JakeDrinkStoreWeb/Areas/Admin/Views/DrinkType/Index.cshtml
@model IEnumerable<DrinkType>
@{
    ViewData["Title"] = "Drink Types List";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Dink Types List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="DrinkType" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Drink Type
            </a>
        </div>
    </div>
    </br>

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th width="50%">
                    Drink Type Name
                </th>
                <th width="30%">
                    Created Date
                </th>
                <th class="text-center" width="10%">Edit</th>
                <th class="text-center" width="10%">Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr class="align-middle">
                    <td>
                        @obj.Name
                    </td>
                    <td>
                        @obj.CreatedDateTime.ToString("dd/MM/yyyy")
                    </td>
                    <td class="text-center">
                        <div class="btn-group" role="group">
                            <a class="btn btn-primary mx-2" asp-area="Admin" asp-controller="DrinkType" asp-action="Edit" asp-route-id="@obj.Id">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                        </div>
                    </td>
                    <td class="text-center">
                        <div class="btn-group" role="group">
                            <a class="btn btn-danger mx-2" asp-area="Admin" asp-controller="DrinkType" asp-action="Delete" asp-route-id="@obj.Id">
                                <i class="bi bi-trash3"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>