JakeDrinkStoreWeb/Areas/Admin/Controllers/ApplicationUserController.cs
using JakeDrinkStore.DataAccess.Repository.IRepository;
using JakeDrinkStore.Models;
using JakeDrinkStore.Models.ViewModels;
using JakeDrinkStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System.ComponentModel;

namespace JakeDrinkStoreWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
	[Authorize(Roles = SD.Role_Admin)]
	public class ApplicationUserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;

        public ApplicationUserController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager)
        { 
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }

        // GET
        public IActionResult Index()
        {
            return View();
        }

        // GET
        public IActionResult Create()
        {
            string registerUrl = "/Identity/Account/Register";
            return Redirect(registerUrl);
        }

        // GET
        /// <summary>
        /// Edit Application User
        /// </summary>
        public IActionResult Edit(string? id)
        {
            ApplicationUser user = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == id);

            var roles = _userManager.GetRolesAsync(user).GetAwaiter().GetResult();

            ApplicationUserVM userVM = new()
            {
                Id = user.Id,
                Name = user.Name,
                StreetAddress = user.StreetAddress,
                Suburb = user.Suburb,
                State = user.State,
                Postcode = user.Postcode,
                PhoneNumber = user.PhoneNumber,
            };

            if (id == null)
            {
                return NotFound();
            }
            else
            {
                return View(user);
            }
        }

        // POST 
        /// <summary>
        /// Edit Application User
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(user.Id))
                {
                    return NotFound();
                }
                else
                {
                    ApplicationUser dbUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == user.Id);

                    _userManager.GetRolesAsync(dbUser).GetAwaiter().GetResult();

                    dbUser.Name = user.Name;
                    dbUser.StreetAddress = user.StreetAddress;
                    dbUser.Suburb = user.Suburb;
                    dbUser.State = user.State;
                    dbUser.Postcode = user.Postcode;
                    dbUser.PhoneNumber = user.PhoneNumber;

                    _unitOfWork.ApplicationUser.Update(dbUser);
                    TempData["success"] = "User updated successfully";
                }
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        #region API CALLS
        // GET
        [HttpGet]
        public IActionResult GetAll()
        {
            var userList = _unitOfWork.ApplicationUser.GetAll();
            return Json(new { data = userList });
        }

        // POST
        [HttpDelete]
        public IActionResult Delete(Guid? id)
        {
            ApplicationUser user = _unitOfWork.ApplicationUser.GetFirstOrDefault(c => c.Id == id.ToString());
            if (user == null)
            {
                return Json(new { success = false, message = "Cannot be deleted - User doesn't exist" });
            }

            // Get the Role of delete User
            IList<string> userRoles = _userManager.GetRolesAsync(user).GetAwaiter().GetResult();

            // If Role is Admin, return Cannot be deleted error
            if (userRoles.Contains("Admin"))
            {
                return Json(new { success = false, message = "Not Allowed - Admin User cannot be deleted" });
            }
            else
            {
                _unitOfWork.ApplicationUser.Remove(user);
                _unitOfWork.Save();
                return Json(new { success = true, message = "User Successfully Deleted" });
            }
        }
        #endregion API CALLS
    }
}

JakeDrinkStoreWeb/ViewComponents/ShoppingCartViewComponent.cs
using JakeDrinkStore.DataAccess.Repository.IRepository;
using JakeDrinkStore.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace JakeDrinkStoreWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // Get Login User
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            // If the user is logged in, get the Session
            if (claim != null)
            {
                // Check if the session has value
                if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
                {
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                // If session doesn't have a value, set session shopping cart count value
                else
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count);
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
            }
            // Clear the Session when the user logged out
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

JakeDrinkStoreWeb/Views/Shared/_HelpButtonPartial.cshtml
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary float" data-bs-toggle="modal" data-bs-target="#exampleModal">
    <i class="bi bi-question my-float"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-primary fw-bold" id="exampleModalLabel">Jake Drink Store Guide</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5 class="text-info fw-bold">User Logins</h5>
                <p>There are three types of Login Users in the Application. Each type of user has different role and access.</p>
                <ul>
                    <li>Admin User - <i class="text-primary fw-bold">admin@jakelin.com.au</i></li>
                    <li>Customer User (Default in Register) - <i class="text-primary fw-bold">customer@jakelin.com.au</i></li>
                    <li>Company User - <i class="text-primary fw-bold">company@jakelin.com.au</i></li>
                </ul>
                <p>The password for all the users is <i class="text-primary fw-bold">Pa$$w0rd</i></p>
                <p>You can also login using your <i class ="text-primary fw-bold">Facebook Account</i> and you won't need to enter Email and Password when you log in again.</p>
                <h5 class="text-info fw-bold">Stripe Payment Card</h5>
                <p>This is a testing card for Stripe Payment. This card can be used when you make a payment in checkout.</p>
                <ul>
                    <li>Card Number - <b class="text-primary">4242 4242 4242 4242</b></li>
                    <li>Expiry Date - <b class="text-primary">12 / 34</b></li>
                    <li>CVC - <b class="text-primary">123</b></li>
                </ul>
            </div>
        </div>
    </div>
</div>

JakeDrinkStoreWeb/Views/Shared/_Layout.cshtml
@using JakeDrinkStore.Utility
@*Inject HttpContextAccessor to access our HttpContext*@
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    string path = Context.Request.Path;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <meta property="og:title" content="Jake Drink Store" />
    <meta property="og:description" content="This is a Drink Store web application built as a personal project using ASP.NET Core MVC. The login information are in the question mark (?) button at the bottom right corner." />
    <meta property="og:image" content="https://cdn.pixabay.com/photo/2018/01/25/08/14/beverages-3105631_960_720.jpg" />
    <meta property="og:url" content="https://jakedrinkstoreweb.azurewebsites.net/"/ >
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body>
    <partial name="_HelpButtonPartial" />
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fw-normal py-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">Jake Drink Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link @(path == "/" ? "active" : "")" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(path.Contains("Order") ? "active" : "")" asp-area="Admin" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle @(!path.Contains("Order") && path.StartsWith("/Admin") ? "active" : "")" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
                                <div class="dropdown-menu">
                                    <a class="nav-link @(path.Contains("Product") ? "active" : "")" asp-area="Admin" asp-controller="Product" asp-action="Index">Drinks</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link @(path.Contains("DrinkType") ? "active" : "")" asp-area="Admin" asp-controller="DrinkType" asp-action="Index">Drink Types</a>
                                    <a class="nav-link @(path.Contains("Tag") ? "active" : "")" asp-area="Admin" asp-controller="Tag" asp-action="Index">Tags</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link @(path.Contains("Company") ? "active" : "")" asp-area="Admin" asp-controller="Company" asp-action="Index">Companies</a>
                                    <a class="nav-link @(path.Contains("User") ? "active" : "")" asp-area="Admin" asp-controller="ApplicationUser" asp-action="Index">Users</a>
                                </div>
                            </li>
                        }
                        @if (!User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item px-2">
                                <a class="nav-link @(path.Contains("Cart") ? "active" : "")" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    @*Call the ShoppingCart ViewComponent*@
                                    @await Component.InvokeAsync("ShoppingCart")
                                </a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Jake Drink Store - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/25vn65pxq2sc6r183scadjh76p6z6an4xtg3jl9z9y7ssfps/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

JakeDrinkStoreWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
            toastr.success('@TempData["success"]');
        </script>
}
@if (TempData["error"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
            toastr.error('@TempData["error"]');
        </script>
}